version: '3'

services:
    db:
        image: wellintton/db
        container_name: db
        restart: always
        tty: true
        command: --innodb-use-native-aio=0
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root       
        networks:
            - node-network
            
    nodeserver:
        image: wellintton/nodeserver
        container_name: nodeserver
        depends_on: 
            - db
        networks:
            - node-network
        tty: true
        ports:
            - "3000:3000"
        command: bash -c "dockerize -wait tcp://db:3306 && node server.js"            
    nginx:
        image: wellintton/nginx
        container_name: nginx
        depends_on: 
            - nodeserver
        tty: true
        ports:
            - "8080:80"
        networks:
            - node-network
            
networks:
    node-network:
        name: node-network
        driver: bridge
